[project]
name = "mens-soccer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.5",
    "tldextract>=5.3.0",
    "playwright>=1.48.0",
    "shot-scraper>=1.6",
]
