```{r}
library(tidyverse)
```

```{r}

teams <- read_csv("../data/input/teams.csv")
rosters25 <- read_csv("../data/raw/csv/rosters_2025_I.csv")
rosters_msoc <- read_csv("../data/raw/csv/rosters_msoc_2025.csv") |> mutate(ncaa_id = as.numeric(ncaa_id))

msoc_keep <- rosters_msoc |> filter(!is.na(url))

combined_rosters <- bind_rows(rosters24, msoc_keep)

unique_roster_teams <- rosters25 |> distinct(ncaa_id)

need_rosters <- teams |> anti_join(unique_roster_teams) |> filter(division == "I")

write_csv(combined_with_adds, "../data/output/combined_rosters_2024.csv")

```


```{r}

rosters <- read_csv("../data/output/combined_rosters_2024.csv")

adds <- read_csv("../data/additions/adds.csv")

combined_with_adds <- bind_rows(rosters, adds)

unique_roster_teams <- combined_with_adds |> distinct(ncaa_id)

need_rosters <- teams |> anti_join(unique_roster_teams)

write_csv(need_rosters, "../data/interim/need_rosters.csv")

write_csv(combined_with_adds, "../data/output/combined_rosters_2024.csv")
```

